;================================================ COVENANT SQUAD DROP CONTROL ============================================================

(global boolean g_sur_drop_spawn TRUE)
(global short g_sur_drop_limit 0)
(global short g_sur_drop_count 0)
(global short g_sur_drop_number 0)

(script dormant survival_drop_spawn
	; set the max number of drop pods at any one time 
	(cond
		((<= (game_coop_player_count) 4)		(set g_sur_drop_limit 1))
		((>= (game_coop_player_count) 5)		(set g_sur_drop_limit 2))
	)
	(sleep (* 30 60 2))

	; stays in this loop forever 
	(sleep_until
		(begin
			(sleep (* 30 180 1))
			(sleep_until 
				(and
					(<= (ai_living_count gr_survival_waves) 10)
					(<= (ai_living_count gr_survival_extras) 0)
					(= (survival_mode_current_wave_is_boss) FALSE)
					(= (survival_mode_current_wave_is_initial) FALSE)
				)
			)
			
			(print "cleaning up drop pods...")
			(sleep 1)
			(ai_erase sq_sur_drop_01)
			(ai_erase sq_sur_drop_02)
			(ai_erase sq_sur_drop_03)
			(ai_erase sq_sur_drop_04)
			(ai_erase sq_sur_drop_05)
				
			(begin_random_count g_sur_drop_limit
				(if g_sur_drop_spawn (wake drop_pod_01))
				(if g_sur_drop_spawn (wake drop_pod_02))
				(if g_sur_drop_spawn (wake drop_pod_03))
				(if g_sur_drop_spawn (wake drop_pod_04))
				(if g_sur_drop_spawn (wake drop_pod_05))
			)
			(sleep 1)
			(sleep_until (<= (ai_living_count gr_survival_extras) 0))
			(sleep 1)
			(set g_sur_drop_count 0)
			(set g_sur_drop_spawn TRUE)
			(sleep 1)
		FALSE)
	)
)

;=============== Covenant Squad Drop 01 =======================================
(script continuous drop_pod_01
	(sleep_forever)
	(sleep (random_range 5 15))
	(print "squad pod 01...")
	(object_create dm_drop_01)
	(ai_place sq_sur_drop_01)
	(sleep 1)
	(set v_sur_drop_01 (ai_vehicle_get_from_spawn_point sq_sur_drop_01/driver))
	(sleep 1)
	(objects_attach dm_drop_01 "" v_sur_drop_01 "")
	(sleep 1)
	(device_set_position dm_drop_01 1)
	(sleep_until (>= (device_get_position dm_drop_01) 0.85) 1)
	(wake drop_blip_01)
	(unit_open v_sur_drop_01)
	(sleep 30)
	(print "kicking ai out of pod 01...")
	(vehicle_unload v_sur_drop_01 "")
	(sleep_until (>= (device_get_position dm_drop_01) 0.98) 1)
	(effect_new_on_object_marker fx\fx_library\pod_impacts\default\pod_impact_default_large.effect dm_drop_01 "fx_impact")
	(sleep_until (>= (device_get_position dm_drop_01) 1) 1)
	(sleep 1)
	(objects_detach dm_drop_01 v_sur_drop_01)
	(object_destroy dm_drop_01)
	(sleep 1)
	(set g_sur_drop_count (+ g_sur_drop_count 1))
	(if (>= g_sur_drop_count g_sur_drop_limit) (set g_sur_drop_spawn FALSE))
)

(script continuous drop_blip_01
	(sleep_forever)
	(print "blipping drop pod 01...")
	(f_survival_callout_dropship v_sur_drop_01)
)

;=============== Covenant Squad Drop 02 =======================================
(script continuous drop_pod_02
	(sleep_forever)
	(sleep (random_range 5 15))
	(print "squad pod 02...")
	(object_create dm_drop_02)
	(ai_place sq_sur_drop_02)
	(sleep 1)
	(set v_sur_drop_02 (ai_vehicle_get_from_spawn_point sq_sur_drop_02/driver))
	(sleep 1)
	(objects_attach dm_drop_02 "" v_sur_drop_02 "")
	(sleep 1)
	(device_set_position dm_drop_02 1)
	(sleep_until (>= (device_get_position dm_drop_02) 0.85) 1)
	(wake drop_blip_02)
	(unit_open v_sur_drop_02)
	(sleep 30)
	(print "kicking ai out of pod 02...")
	(vehicle_unload v_sur_drop_02 "")
	(sleep_until (>= (device_get_position dm_drop_02) 0.98) 1)
	(effect_new_on_object_marker fx\fx_library\pod_impacts\default\pod_impact_default_large.effect dm_drop_02 "fx_impact")
	(sleep_until (>= (device_get_position dm_drop_02) 1) 1)
	(sleep 1)
	(objects_detach dm_drop_02 v_sur_drop_02)
	(object_destroy dm_drop_02)
	(sleep 1)
	(set g_sur_drop_count (+ g_sur_drop_count 1))
	(if (>= g_sur_drop_count g_sur_drop_limit) (set g_sur_drop_spawn FALSE))
)

(script continuous drop_blip_02
	(sleep_forever)
	(print "blipping drop pod 02...")
	(f_survival_callout_dropship v_sur_drop_02)
)

;=============== Covenant Squad Drop 03 =======================================
(script continuous drop_pod_03
	(sleep_forever)
	(sleep (random_range 5 15))
	(print "squad pod 03...")
	(object_create dm_drop_03)
	(ai_place sq_sur_drop_03)
	(sleep 1)
	(set v_sur_drop_03 (ai_vehicle_get_from_spawn_point sq_sur_drop_03/driver))
	(sleep 1)
	(objects_attach dm_drop_03 "" v_sur_drop_03 "")
	(sleep 1)
	(device_set_position dm_drop_03 1)
	(sleep_until (>= (device_get_position dm_drop_03) 0.85) 1)
	(wake drop_blip_03)
	(unit_open v_sur_drop_03)
	(sleep 30)
	(print "kicking ai out of pod 03...")
	(vehicle_unload v_sur_drop_03 "")
	(sleep_until (>= (device_get_position dm_drop_03) 0.98) 1)
	(effect_new_on_object_marker fx\fx_library\pod_impacts\default\pod_impact_default_large.effect dm_drop_03 "fx_impact")
	(sleep_until (>= (device_get_position dm_drop_03) 1) 1)
	(sleep 1)
	(objects_detach dm_drop_03 v_sur_drop_03)
	(object_destroy dm_drop_03)
	(sleep 1)
	(set g_sur_drop_count (+ g_sur_drop_count 1))
	(if (>= g_sur_drop_count g_sur_drop_limit) (set g_sur_drop_spawn FALSE))
)

(script continuous drop_blip_03
	(sleep_forever)
	(print "blipping drop pod 03...")
	(f_survival_callout_dropship v_sur_drop_03)
)

;=============== Covenant Squad Drop 04 =======================================
(script continuous drop_pod_04
	(sleep_forever)
	(sleep (random_range 5 15))
	(print "squad pod 04...")
	(object_create dm_drop_04)
	(ai_place sq_sur_drop_04)
	(sleep 1)
	(set v_sur_drop_04 (ai_vehicle_get_from_spawn_point sq_sur_drop_04/driver))
	(sleep 1)
	(objects_attach dm_drop_04 "" v_sur_drop_04 "")
	(sleep 1)
	(device_set_position dm_drop_04 1)
	(sleep_until (>= (device_get_position dm_drop_04) 0.85) 1)
	(wake drop_blip_04)
	(unit_open v_sur_drop_04)
	(sleep 30)
	(print "kicking ai out of pod 04...")
	(vehicle_unload v_sur_drop_04 "")
	(sleep_until (>= (device_get_position dm_drop_04) 0.98) 1)
	(effect_new_on_object_marker fx\fx_library\pod_impacts\default\pod_impact_default_large.effect dm_drop_04 "fx_impact")
	(sleep_until (>= (device_get_position dm_drop_04) 1) 1)
	(sleep 1)
	(objects_detach dm_drop_04 v_sur_drop_04)
	(object_destroy dm_drop_04)
	(sleep 1)
	(set g_sur_drop_count (+ g_sur_drop_count 1))
	(if (>= g_sur_drop_count g_sur_drop_limit) (set g_sur_drop_spawn FALSE))
)

(script continuous drop_blip_04
	(sleep_forever)
	(print "blipping drop pod 04...")
	(f_survival_callout_dropship v_sur_drop_04)
)


;=============== Covenant Squad Drop 05 =======================================
(script continuous drop_pod_05
	(sleep_forever)
	(sleep (random_range 5 15))
	(print "squad pod 05...")
	(object_create dm_drop_05)
	(ai_place sq_sur_drop_05)
	(sleep 1)
	(set v_sur_drop_05 (ai_vehicle_get_from_spawn_point sq_sur_drop_05/driver))
	(sleep 1)
	(objects_attach dm_drop_05 "" v_sur_drop_05 "")
	(sleep 1)
	(device_set_position dm_drop_05 1)
	(sleep_until (>= (device_get_position dm_drop_05) 0.85) 1)
	(wake drop_blip_05)
	(unit_open v_sur_drop_05)
	(sleep 30)
	(print "kicking ai out of pod 05...")
	(vehicle_unload v_sur_drop_05 "")
	(sleep_until (>= (device_get_position dm_drop_05) 0.97) 1)
	(effect_new_on_object_marker fx\fx_library\pod_impacts\water\pod_impact_water_large.effect dm_drop_05 "fx_impact")
	(sleep_until (>= (device_get_position dm_drop_05) 1) 1)
	(sleep 1)
	(objects_detach dm_drop_05 v_sur_drop_05)
	(object_destroy dm_drop_05)
	(sleep 1)
	(set g_sur_drop_count (+ g_sur_drop_count 1))
	(if (>= g_sur_drop_count g_sur_drop_limit) (set g_sur_drop_spawn FALSE))
)

(script continuous drop_blip_05
	(sleep_forever)
	(print "blipping drop pod 05...")
	(f_survival_callout_dropship v_sur_drop_05)
)
